In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
rt_df = pd.read_csv('/content/drive/MyDrive/Routes_by_Transportation_Sites_20241020.csv')
print(rt_df.head())

  School_Year Route_Number  OPT_Code
0   2015-2016         J698     75004
1   2015-2016         J699     75580
2   2015-2016         J700     75003
3   2015-2016         J700     75140
4   2015-2016         J701     75003

In [54]:
ts_df = pd.read_csv('/content/drive/MyDrive/Transportation_Sites_20241020 (1).csv')
print(ts_df.head())

  School_Year OPT_Code                            Name     Affiliation  \
0   2016-2017    01001  Comprehensive Kids Devel. Scho  Other Religion
1   2016-2017    01569           BARD HS EARLY COLLEGE          Public
2   2016-2017    01600               SATELLITE ACADEMY          Public
3   2016-2017    01616         COOK CTR GRAMMAR SCHOOL    Nonsectarian
4   2016-2017    01657        MANHATTAN CHARTER SCHOOL         Charter

  Site_Type           Street_Address       City State      Zip  Longitude  \
0    School       101 Norfolk Street  Manhattan    NY  10002.0 -73.987271
1    School  525 EAST HOUSTON STREET  Manhattan    NY  10002.0 -73.975438
2    School       198 FORSYTH STREET  Manhattan    NY  10002.0 -73.990635
3    School       219 STANTON STREET  Manhattan    NY  10002.0 -73.982171
4    School      100 ATTORNEY STREET  Manhattan    NY  10002.0 -73.984365

    Latitude Door_To_Door_Service Stop_To_School_Service  \
0  40.718791                  Yes                     No
1  40.718761                  Yes                     No
2  40.722491                   No                     No
3  40.719442                  Yes                     No
4  40.718346                  Yes                    Yes

  Common_Carrier_Svc_Metrocards Site_Reimbursement Mid_Day_Service  \
0                            No                 No              No
1                           Yes                 No              No
2                           Yes                 No              No
3                           Yes                 No             Yes
4                           Yes                 No             Yes

  D2D_Late_Day_Programs S2S_Late_Day_Programs
0                    No                    No
1                    No                    No
2                    No                    No
3                    No                    No
4                    No                    No

In [55]:
pk_df = pd.read_csv('/content/drive/MyDrive/PreK_Riders_by_Transportation_Site_20241020.csv')
print(pk_df.head())

  School_Year OPT_Code                                Site_Name  \
0   2017-2018     C225              Highbridge Advisory Council
1   2019-2020    C275A              Highbridge Advisory Council
2   2019-2020    C275B              Highbridge Advisory Council
3   2019-2020     C278              Highbridge Advisory Council
4   2017-2018     E011  Crossroads School for Child Development

                               School_Name  Number_of_Riders
0                         Marshall England                50
1              Highbridge Advisory Council                67
2              Highbridge Advisory Council                16
3              Highbridge Advisory Council                12
4  Crossroads School for Child Development                 2

In [56]:
rt_df

       School_Year Route_Number  OPT_Code
0        2015-2016         J698     75004
1        2015-2016         J699     75580
2        2015-2016         J700     75003
3        2015-2016         J700     75140
4        2015-2016         J701     75003
...            ...          ...       ...
129742   2019-2020         Y900     10009
129743   2019-2020         Z001     12486
129744   2019-2020         Z002     75404
129745   2019-2020         Z003     75944
129746   2019-2020         Z007     75912

[129747 rows x 3 columns]

In [57]:
ts_df

,School_Year,OPT_Code,Name,Affiliation,Site_Type,Street_Address,City,State,Zip,Longitude,Latitude,Door_To_Door_Service,Stop_To_School_Service,Common_Carrier_Svc_Metrocards,Site_Reimbursement,Mid_Day_Service,D2D_Late_Day_Programs,S2S_Late_Day_Programs
0,2016-2017,01001,Comprehensive Kids Devel. Scho,Other Religion,School,101 Norfolk Street,Manhattan,NY,10002.0,-7.398727e+01,40.718791,Yes,No,No,No,No,No,No
1,2016-2017,01569,BARD HS EARLY COLLEGE,Public,School,525 EAST HOUSTON STREET,Manhattan,NY,10002.0,-7.397544e+01,40.718761,Yes,No,Yes,No,No,No,No
2,2016-2017,01600,SATELLITE ACADEMY,Public,School,198 FORSYTH STREET,Manhattan,NY,10002.0,-7.399063e+01,40.722491,No,No,Yes,No,No,No,No
3,2016-2017,01616,COOK CTR GRAMMAR SCHOOL,Nonsectarian,School,219 STANTON STREET,Manhattan,NY,10002.0,-7.398217e+01,40.719442,Yes,No,Yes,No,Yes,No,No
4,2016-2017,01657,MANHATTAN CHARTER SCHOOL,Charter,School,100 ATTORNEY STREET,Manhattan,NY,10002.0,-7.398436e+01,40.718346,Yes,Yes,Yes,No,Yes,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22886,2019-2020,S463,NEW YORK CITY TARGETED PLUS PROGRAM,NaN,Pre-K/EI Site,1180 TINTON AVENUE,Bronx,NY,10456.0,1.011725e+06,241108.000000,Yes,No,No,No,No,No,No
22887,2019-2020,S533,District 07/Learning Through Play Pre K Center,NaN,Pre-K/EI Site,105 Willis Avenue,Bronx,NY,10454.0,1.004927e+06,232856.000000,Yes,No,No,No,No,No,No
22888,2019-2020,S534,Z029 Learning Through Play Pre-K Center,NaN,Pre-K/EI Site,535 Union Avenue,Bronx,NY,10455.0,1.010390e+06,235149.000000,Yes,No,No,No,No,No,No
22889,2019-2020,S535,Z087 Rose Hill Pre-K Center,NaN,Pre-K/EI Site,2512 Marion Avenue,Bronx,NY,10458.0,1.013782e+06,253096.000000,Yes,No,No,No,No,No,No
22890,2019-2020,X188,PS188X @34x,NaN,Pre-K/EI Site,770 Grote St,Bronx,NY,10473.0,1.016413e+06,249181.000000,Yes,No,No,No,No,No,No

In [58]:
pk_df

,School_Year,OPT_Code,Site_Name,School_Name,Number_of_Riders
0,2017-2018,C225,Highbridge Advisory Council,Marshall England,50
1,2019-2020,C275A,Highbridge Advisory Council,Highbridge Advisory Council,67
2,2019-2020,C275B,Highbridge Advisory Council,Highbridge Advisory Council,16
3,2019-2020,C278,Highbridge Advisory Council,Highbridge Advisory Council,12
4,2017-2018,E011,Crossroads School for Child Development,Crossroads School for Child Development,2
...,...,...,...,...,...
1623,2019-2020,S409,Z100 District 25 Pre-K Center,New York City Public School Pre-K Center,22
1624,2019-2020,S449,District 9/P.449X,New York City Public School,5
1625,2019-2020,S582,District 9/Garden of Learning & Discovery Pre ...,New York City Public School Pre-K Center,7
1626,2019-2020,S596,"Citywide/District 75, District 11 SC P.596@178X",New York City Public School,24
1627,2019-2020,S633,New york city Public school Prek Center,Z023 Mosaic Prek Center,19

In [59]:
ts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22891 entries, 0 to 22890
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   School_Year                    22891 non-null  object
 1   OPT_Code                       22891 non-null  object
 2   Name                           22891 non-null  object
 3   Affiliation                    20594 non-null  object
 4   Site_Type                      22891 non-null  object
 5   Street_Address                 22891 non-null  object
 6   City                           22891 non-null  object
 7   State                          22881 non-null  object
 8   Zip                            22881 non-null  float64
 9   Longitude                      22891 non-null  float64
 10  Latitude                       22891 non-null  float64
 11  Door_To_Door_Service           22891 non-null  object
 12  Stop_To_School_Service         22891 non-null  object
 13  Common_Carrier_Svc_Metrocards  22891 non-null  object
 14  Site_Reimbursement             22891 non-null  object
 15  Mid_Day_Service                22891 non-null  object
 16  D2D_Late_Day_Programs          22891 non-null  object
 17  S2S_Late_Day_Programs          22891 non-null  object
dtypes: float64(3), object(15)
memory usage: 3.1+ MB

In [60]:
rt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129747 entries, 0 to 129746
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   School_Year   129747 non-null  object
 1   Route_Number  129747 non-null  object
 2   OPT_Code      129747 non-null  int64
dtypes: int64(1), object(2)
memory usage: 3.0+ MB

In [61]:
pk_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1628 entries, 0 to 1627
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   School_Year       1628 non-null   object
 1   OPT_Code          1628 non-null   object
 2   Site_Name         1628 non-null   object
 3   School_Name       1624 non-null   object
 4   Number_of_Riders  1628 non-null   int64
dtypes: int64(1), object(4)
memory usage: 63.7+ KB

In [62]:
rt_df.isnull().sum()

School_Year     0
Route_Number    0
OPT_Code        0
dtype: int64

In [63]:
ts_df.isnull().sum()

School_Year                         0
OPT_Code                            0
Name                                0
Affiliation                      2297
Site_Type                           0
Street_Address                      0
City                                0
State                              10
Zip                                10
Longitude                           0
Latitude                            0
Door_To_Door_Service                0
Stop_To_School_Service              0
Common_Carrier_Svc_Metrocards       0
Site_Reimbursement                  0
Mid_Day_Service                     0
D2D_Late_Day_Programs               0
S2S_Late_Day_Programs               0
dtype: int64

In [64]:
pk_df.isnull().sum()

School_Year         0
OPT_Code            0
Site_Name           0
School_Name         4
Number_of_Riders    0
dtype: int64

In [65]:
# Fill missing values in numerical columns with the mean
for column in ts_df.select_dtypes(include=np.number):
  ts_df[column].fillna(ts_df[column].mean(), inplace=True)

# Fill missing values in categorical columns with the mode
for column in ts_df.select_dtypes(include='object'):
  ts_df[column].fillna(ts_df[column].mode()[0], inplace=True)

print(ts_df.isnull().sum())

School_Year                      0
OPT_Code                         0
Name                             0
Affiliation                      0
Site_Type                        0
Street_Address                   0
City                             0
State                            0
Zip                              0
Longitude                        0
Latitude                         0
Door_To_Door_Service             0
Stop_To_School_Service           0
Common_Carrier_Svc_Metrocards    0
Site_Reimbursement               0
Mid_Day_Service                  0
D2D_Late_Day_Programs            0
S2S_Late_Day_Programs            0
dtype: int64

<ipython-input-65-9adf0aecb280>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ts_df[column].fillna(ts_df[column].mean(), inplace=True)
<ipython-input-65-9adf0aecb280>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ts_df[column].fillna(ts_df[column].mode()[0], inplace=True)

In [66]:
# Fill missing values in numerical columns with the mean
for column in pk_df.select_dtypes(include=np.number):
  pk_df[column].fillna(pk_df[column].mean(), inplace=True)

# Fill missing values in categorical columns with the mode
for column in pk_df.select_dtypes(include='object'):
  pk_df[column].fillna(pk_df[column].mode()[0], inplace=True)

print(pk_df.isnull().sum())

School_Year         0
OPT_Code            0
Site_Name           0
School_Name         0
Number_of_Riders    0
dtype: int64

<ipython-input-66-51faf56e0e23>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pk_df[column].fillna(pk_df[column].mean(), inplace=True)
<ipython-input-66-51faf56e0e23>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pk_df[column].fillna(pk_df[column].mode()[0], inplace=True)

In [67]:
print("Column names for rt_df:")
print(rt_df.columns.tolist())
print("\nColumn names for ts_df:")
print(ts_df.columns.tolist())
print("\nColumn names for pk_df:")
print(pk_df.columns.tolist())

Column names for rt_df:
['School_Year', 'Route_Number', 'OPT_Code']

Column names for ts_df:
['School_Year', 'OPT_Code', 'Name', 'Affiliation', 'Site_Type', 'Street_Address', 'City', 'State', 'Zip', 'Longitude', 'Latitude', 'Door_To_Door_Service', 'Stop_To_School_Service', 'Common_Carrier_Svc_Metrocards', 'Site_Reimbursement', 'Mid_Day_Service', 'D2D_Late_Day_Programs', 'S2S_Late_Day_Programs']

Column names for pk_df:
['School_Year', 'OPT_Code', 'Site_Name', 'School_Name', 'Number_of_Riders']

In [68]:
common_columns = set(rt_df.columns) & set(ts_df.columns) & set(pk_df.columns)
print("Common columns in all three DataFrames:")
print(list(common_columns))

Common columns in all three DataFrames:
['OPT_Code', 'School_Year']

In [69]:
# Convert 'OPT_Code' to a consistent data type (e.g., string) in all DataFrames before merging
rt_df['OPT_Code'] = rt_df['OPT_Code'].astype(str)
ts_df['OPT_Code'] = ts_df['OPT_Code'].astype(str)
pk_df['OPT_Code'] = pk_df['OPT_Code'].astype(str)

merged_df = rt_df.merge(ts_df, on=['School_Year', 'OPT_Code'])
merged_df = merged_df.merge(pk_df, on=['School_Year', 'OPT_Code'])

In [71]:
# Filter for routes with a specific number
filtered_df = merged_df[merged_df['Route_Number'] == 123]

# Filter for schools with a specific name
filtered_df = merged_df[merged_df['School_Name'] == 'Central High']
filtered_df

Empty DataFrame
Columns: [School_Year, Route_Number, OPT_Code, Name, Affiliation, Site_Type, Street_Address, City, State, Zip, Longitude, Latitude, Door_To_Door_Service, Stop_To_School_Service, Common_Carrier_Svc_Metrocards, Site_Reimbursement, Mid_Day_Service, D2D_Late_Day_Programs, S2S_Late_Day_Programs, Site_Name, School_Name, Number_of_Riders]
Index: []

[0 rows x 22 columns]

In [72]:
grouped_df = merged_df.groupby('Route_Number')['Number_of_Riders'].sum().reset_index()
grouped_df

Empty DataFrame
Columns: [Route_Number, Number_of_Riders]
Index: []

In [73]:
grouped_df = merged_df.groupby('OPT_Code')[['Door_To_Door_Service', 'Stop_To_School_Service', 'Common_Carrier_Svc_Metrocards']].sum().reset_index()
grouped_df

Empty DataFrame
Columns: [OPT_Code, Door_To_Door_Service, Stop_To_School_Service, Common_Carrier_Svc_Metrocards]
Index: []

In [75]:
high_utilization_sites = merged_df.nlargest(10, 'Number_of_Riders')
high_utilization_sites

Empty DataFrame
Columns: [School_Year, Route_Number, OPT_Code, Name, Affiliation, Site_Type, Street_Address, City, State, Zip, Longitude, Latitude, Door_To_Door_Service, Stop_To_School_Service, Common_Carrier_Svc_Metrocards, Site_Reimbursement, Mid_Day_Service, D2D_Late_Day_Programs, S2S_Late_Day_Programs, Site_Name, School_Name, Number_of_Riders]
Index: []

[0 rows x 22 columns]

In [76]:
merged_df = rt_df.merge(ts_df, on=['School_Year', 'OPT_Code'])

In [77]:
print("Shape of rt_df:", rt_df.shape)
print("Shape of ts_df:", ts_df.shape)
print("Shape of pk_df:", pk_df.shape)

merged_df = rt_df.merge(ts_df, on=['School_Year', 'OPT_Code'])
print("Shape of merged_df:", merged_df.shape)

final_df = merged_df.merge(pk_df, on=['School_Year', 'OPT_Code'])
print("Shape of final_df:", final_df.shape)

Shape of rt_df: (129747, 3)
Shape of ts_df: (22891, 18)
Shape of pk_df: (1628, 5)
Shape of merged_df: (96547, 19)
Shape of final_df: (0, 22)

In [78]:
merged_df

,School_Year,Route_Number,OPT_Code,Name,Affiliation,Site_Type,Street_Address,City,State,Zip,Longitude,Latitude,Door_To_Door_Service,Stop_To_School_Service,Common_Carrier_Svc_Metrocards,Site_Reimbursement,Mid_Day_Service,D2D_Late_Day_Programs,S2S_Late_Day_Programs
0,2015-2016,J698,75004,BEN PORAT YOSEF,Yeshiva,School,EAST 243 FRISCH COURT,New Jersey,NJ,7652.0,-74.050276,40.917161,Yes,No,No,No,No,No,No
1,2015-2016,J699,75580,SINAI MA'AYANOT HS FOR GIRLS,Yeshiva,School,1650 PALISADE AVE,New Jersey,NJ,7666.0,-74.002739,40.906526,Yes,No,Yes,No,No,No,No
2,2015-2016,J700,75003,"THE COMMUNITY SCHOOL, INC",Nonsectarian,School,11 W FOREST AVE,New Jersey,NJ,7666.0,-74.002203,40.893988,Yes,No,No,No,No,No,No
3,2015-2016,J700,75140,"THE COMMUNITY SCHOOL, INC.",Nonsectarian,School,1135 TEANECK ROAD,New Jersey,NJ,7666.0,-74.002004,40.893616,Yes,No,Yes,No,No,No,No
4,2015-2016,J701,75003,"THE COMMUNITY SCHOOL, INC",Nonsectarian,School,11 W FOREST AVE,New Jersey,NJ,7666.0,-74.002203,40.893988,Yes,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96542,2019-2020,Y900,10009,P.S. 9,Public,School,230 EAST 183 STREET,Bronx,NY,10458.0,-73.899412,40.857144,Yes,Yes,Yes,No,Yes,No,No
96543,2019-2020,Z001,12486,P186X @ WALTER J. DAMROSCH,Public,School,750 JENNINGS STREET,Bronx,NY,10459.0,-73.897559,40.831793,Yes,No,Yes,No,Yes,Yes,No
96544,2019-2020,Z002,75404,WESTCHESTER SCH FOR SP CHILDRE,Nonsectarian,School,45 PARK AVENUE,Westchester,NY,10703.0,-73.891930,40.941268,Yes,No,No,No,No,No,No
96545,2019-2020,Z003,75944,MT PLEASANT BLYTHEDALE UFSD,Non-NYC Public,School,95 BRADHURST AVE,Westchester,NY,10595.0,-73.802740,41.094860,Yes,No,No,No,No,No,No
96546,2019-2020,Z007,75912,Cerebral Palsy of Westchester,Nonsectarian,School,1186 KING STREET,Westchester,NY,10573.0,-73.663398,41.002962,Yes,No,No,No,No,No,No

In [80]:
merged_df.to_csv('/content/drive/MyDrive/final_dataset.csv', index=False)